parameters:
  pool: ''

jobs:
- job: Wasm_UITests
  container: nv-bionic-wasm

  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    NUGET_PACKAGES: $(build.sourcesdirectory)/.nuget

  steps:
  - checkout: self
    clean: true

  - bash: |
      source /emsdk/emsdk_env.sh
      msbuild /r /p:Configuration=Release /t:restore src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
      msbuild /p:Configuration=Release /p:TargetFramework=netstandard2.0 src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj /p:UnoSourceGeneratorUseGenerationHost=true /p:UnoSourceGeneratorUseGenerationController=false

    displayName: 'Build sample app'

  - bash: |
      cd $(build.sourcesdirectory)/src/SamplesApp/SamplesApp.Wasm/bin/Release/netstandard2.0/dist
      python server.py &
      cd $(build.sourcesdirectory)/src/SamplesApp/SamplesApp.Wasm.UITests
      npm install
      node app

    displayName: 'Running UI Tests'

  - task: CopyFiles@2
    displayName: 'Publish Wasm Tests results'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/src/SamplesApp/SamplesApp.Wasm.UITests/out
      Contents: '**/*.*'
      TargetFolder: $(build.artifactstagingdirectory)/screenshots
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: wasm-uitests
      ArtifactType: Container

- job: Wasm_UITests_Compare
  dependsOn: Wasm_UITests

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - checkout: self
    clean: true

  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.9.1
      checkLatest: false

  - task: MSBuild@1
    inputs:
      solution: src/Uno.UI.TestComparer/Uno.UI.TestComparer.csproj
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r "/p:Configuration=Release"
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false

  - script: |
      src\Uno.UI.TestComparer\bin\Release\net461\Uno.UI.TestComparer.exe "azdo" "$(UITestsCompare_PAT)" "$(build.artifactstagingdirectory)" "%GIT_SOURCEBRANCH%" "%GIT_TARGETBRANCH%" "wasm-uitests" "$(Build.DefinitionName)" "$(System.TeamProject)" "$(System.TeamFoundationCollectionUri)" "$(Build.BuildId)" "3"
      
    env:
      GIT_TARGETBRANCH: "$(System.PullRequest.TargetBranch)"
      GIT_SOURCEBRANCH: "$(Build.SourceBranch)"
    displayName: 'Compare UI Tests screenshots'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: wasm-uitests-compare-results
      ArtifactType: Container
